IF
	Global("pxfolow","LOCALS",1)
THEN
	RESPONSE #100
		LeaveParty()
		ChangeAIScript("",DEFAULT)
		SetLeavePartyDialogFile()
		ChangeEnemyAlly(Myself,FAMILIAR)
		AddFamiliar()
		ReallyForceSpellRES("pxflvisi",Myself)
		SetGlobal("pxfolow","LOCALS",2)
END

IF
	Global("pxfolow","LOCALS",2)
	InParty(Myself)
THEN
	RESPONSE #100
		ReallyForceSpellRES("pxflresu",Myself)
		SetGlobal("pxfolow","LOCALS",0)
END